version: 2

refs:
  container: &container
    docker:
      - image: node:10
        environment:
          DATABASE_URL: 'postgres://postgres@127.0.0.1:9000/componentstore'
      - image: postgres:10.6-alpine
        environment:
          POSTGRES_USER: postgres
          POSTGRES_DB: componentstore

    working_directory: component_store

  steps:
    - &Install
      run:
        name: Install Dependencies
        command: npm install --frozen-lockfile
    - &Test
      run:
        name: Test
        command: npm ci:test
    - &Run_Migrations
      run:
        name: Run migrations
        command: npm migrations:test

jobs:
  all:
    <<: *container
    steps:
      - checkout
      - *Install
      - *Run_Migrations
      - *Test

  deploy-staging:
    <<: *container
    steps:
      - checkout
      - *Install
      - *Run_Migrations
      - *Test
      - run: echo "Run migrations on staging db"
      - run: echo "Deploy to staging"
      - run: echo "Post to slack - deployment waiting for approval"
      - run:
          name: Post to Slack on FAILURE
          command: echo "Post to slack - staging build failed"
          when: on_fail

  deploy-prod:
    <<: *container
    steps:
      - checkout
      - *Install
      - *Run_Migrations
      - *Test
      - run: echo "Run migrations on production db"
      - run: echo "Deploy to production"
      - run:
          name: Post to Slack on FAILURE
          command: echo "Post to slack - production build failed"
          when: on_fail

  nightly:
    <<: *container
    steps:
      - checkout
      - *Install
      - *Test
      - run:
          name: Post to Slack on FAILURE
          command: echo "Post to slack - nightly build failed"
          when: on_fail

workflows:
  version: 2
  all:
    jobs:
      - all:
          filters:
            branches:
              ignore:
                - main

  main:
    jobs:
      - deploy-staging:
          filters:
            branches:
              only: main
      - approve-prod:
          type: approval
          requires:
            - deploy-staging
          filters:
            branches:
              only: main
      - deploy-prod:
          requires:
            - approve-prod
          filters:
            branches:
              only: main

  nightly:
    triggers:
      - schedule:
          cron: '0 1 * * *'
          filters:
            branches:
              only: main
    jobs:
      - nightly