version: "3.5"

services:

  postgres:
    image: postgres:14.7-bullseye
    container_name: componento_db12
    environment:
      POSTGRES_USER: ${DB_USER:-componento}
      POSTGRES_PASSWORD: ${DB_PASS:-secret}
      POSTGRES_DB: ${DB_DATABASE:-componentstore}
      PGDATA: /var/lib/postgresql/data
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "${DB_PORT:-5432}:5432"
# uncomment for sql debug
    command:
      ["postgres", "-c", "log_statement=Mod"]
volumes: 
  pgdata:
