version: "3.5"

services:

  postgres:
    image: postgres:14.7-bullseye
    container_name: componento_db
    environment:
      POSTGRES_USER: ${DB_USER:-componento}
      POSTGRES_PASSWORD: ${DB_PASS:-secret}
      POSTGRES_DB: ${DB_DATABASE:-componentstore}
      PGDATA: /var/lib/postgresql/data
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "${DB_PORT:-5432}:5432"
    # uncomment for sql debug
    command:
      ["postgres", "-c", "log_statement=Mod"]

  postgres-test:
    image: postgres:14.7-bullseye
    container_name: componento_db_test
    environment:
      POSTGRES_USER: ${DB_USER:-componento}
      POSTGRES_PASSWORD: ${DB_PASS_TEST:-secret}
      POSTGRES_DB: ${DB_DATABASE_TEST:-component-store-test}
      PGDATA: /var/lib/postgresql/data
    volumes:
      - pgdatatest:/var/lib/postgresql/data
    ports:
      - "${DB_PORT_TEST:-5433}:5432"
    # uncomment for sql debug
    command:
      ["postgres", "-c", "log_statement=Mod"]

  frontend-test:
    image: postgres:14.7-bullseye
    container_name: componento_frontend_test
    environment:
      POSTGRES_USER: ${DB_USER:-componento}
      POSTGRES_PASSWORD: ${DB_PASS_TEST:-secret}
      POSTGRES_DB: ${DB_DATABASE_TEST:-component-frontend-test}
      PGDATA: /var/lib/postgresql/data
    volumes:
      - pgdatatest1:/var/lib/postgresql/data
    ports:
      - 3006:3000
    # uncomment for sql debug
    command:
      ["postgres", "-c", "log_statement=Mod"]
volumes: 
  pgdata:
  pgdatatest:
  pgdatatest1:
