name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  #Allows you to run this workflow manually from the Action tab
  #workflow_dispatch:
  
jobs:
    
    build-container:

      runs-on: ubuntu-latest

      steps:
    
      - uses: actions/checkout@v3
      - name: Build the Docker image
        working-directory: component_store
        run: docker build . --file Dockerfile --tag componento:$(date +%s)
